/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `Device_Log_after_insert` AFTER INSERT ON `Device_Log` FOR EACH ROW BEGIN

if NEW.Status = "fail" AND NEW.Error_Value = "404_not_found" then
	UPDATE Devices SET Updates_Disabled_Date = NOW() + INTERVAL 7 DAY WHERE Device_ID = NEW.Device_ID;
END if;

if NEW.Status = "fail" AND NEW.Error_Value = "failed_to_update" then
	UPDATE Devices SET Updates_Disabled_Date = NOW() + INTERVAL 3 DAY WHERE Device_ID = NEW.Device_ID;
END if;
	
if NEW.Status = "fail" AND NEW.Error_Value = "eeprom_size_not_enough" then
	UPDATE Devices SET Updates_Disabled_Date = NOW() + INTERVAL 3 DAY WHERE Device_ID = NEW.Device_ID;
END if;

END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
