/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `Firmware_Instances` (
  `FW_IN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_Next` int(11) DEFAULT NULL,
  `FW_ID` int(11) NOT NULL,
  `Device_Type` int(11) NOT NULL,
  PRIMARY KEY (`FW_IN_ID`) USING BTREE,
  KEY `FK_Firmware_Instances_Firmwares` (`FW_ID`),
  KEY `FK_Firmware_Instances_Firmware_Instances` (`FW_Next`),
  KEY `FK_Firmware_Instances_Device_Types` (`Device_Type`),
  CONSTRAINT `FK_Firmware_Instances_Device_Types` FOREIGN KEY (`Device_Type`) REFERENCES `Device_Types` (`Type_ID`),
  CONSTRAINT `FK_Firmware_Instances_Firmware_Instances` FOREIGN KEY (`FW_Next`) REFERENCES `Firmware_Instances` (`FW_IN_ID`),
  CONSTRAINT `FK_Firmware_Instances_Firmwares` FOREIGN KEY (`FW_ID`) REFERENCES `Firmwares` (`FW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
