/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `Firmwares` (
  `FW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FW_Link` varchar(255) NOT NULL,
  `FW_VER` int(11) NOT NULL,
  `IS_EEPROM_Updater` bit(1) NOT NULL,
  PRIMARY KEY (`FW_ID`),
  KEY `FK_Firmwares_Firmware_Versions` (`FW_VER`),
  CONSTRAINT `FK_Firmwares_Firmware_Versions` FOREIGN KEY (`FW_VER`) REFERENCES `Firmware_Versions` (`FW_VER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
